
name: CICD

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
    
      run: mvn package --file pom.xml
      
    - name: trivy file scan
      run: trivy fs --format table -o outputfs.html .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image
      run: docker build -t kokareamol/devtaskmaster:latest .

    - name: trivy image scan
      run: trivy image --format table -o image.html kokareamol/devtaskmaster:latest

    - name: docker login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: docker push kokareamol/devtaskmaster:latest

    - name: kubectl action
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: kubectl apply -f deployment-service.yml
      
          
    
      

    
   
